 import type { Metadata } from "next";
import { Inter } from "next/font/google";
  import "./globals.css";
import Nav from "./component/navbar";
import Product from "./products/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <h1>kuch sochna prega</h1>
       
       
        <Nav/>
        {children}</body>
    </html>
  );
}
